# Generated by Django 4.1.9 on 2023-05-05 14:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('primary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'uploaded file',
                'verbose_name_plural': 'uploaded files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatDataItem',
            fields=[
                ('primary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField()),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=255)),
                ('fact_qliq_data1', models.FloatField()),
                ('fact_qliq_data2', models.FloatField()),
                ('fact_qoil_data1', models.FloatField()),
                ('fact_qoil_data2', models.FloatField()),
                ('forecast_qliq_data1', models.FloatField()),
                ('forecast_qliq_data2', models.FloatField()),
                ('forecast_qoil_data1', models.FloatField()),
                ('forecast_qoil_data2', models.FloatField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.uploadedfile')),
            ],
            options={
                'ordering': ['file', 'id'],
            },
        ),
    ]
